
application:
  title: Microservicios de Reservas
  version: 1.0.0
  author: Galaxy Training

server:
  port: 8083
#  servlet:
#    context-path: /ms-reservas
    
# Oracle #
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: MS_RESERVA
    password: 123
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
  
#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true   
  endpoints:
      web:
        exposure:
          include: "*"
  metrics:
    export:
      prometheus:
        enabled: true


  
  
   