
application:
  title: Microservicios de Pasajeros
  version: 1.0.0
  author: Galaxy Training

server:
  port: 8082
#  servlet:
#    context-path: /ms-pasajeros
    
# MySQL #
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_Pasajero?serverTimezone=GMT-6
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    
# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
  
#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true   
  endpoints:
      web:
        exposure:
          include: "*"
  metrics:
    export:
      prometheus:
        enabled: true


  
  
   