
application:
  title: Microservicios de Reservas-Saga
  version: 1.0.0
  author: Galaxy Training

server:
  port: 8090

# Oracle #
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: MS_RESERVA
    password: 123
    driver-class-name: oracle.jdbc.driver.OracleDriver
      
# Apache Kafka #
custom:
  kafka:
    bootstrap-servers: localhost:9092
    topic-name: topic-saga-consulta
    topic-name-cd: topic-consulta-disponibilidad
    group-id: group-id-saga
    group-id-cd: group-id-consulta-disponibilidad
    
# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
  
#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true   
  endpoints:
      web:
        exposure:
          include: "*"
  metrics:
    export:
      prometheus:
        enabled: true


  
  
   